export const SOCKET_CONNECTION_INIT = "SOCKET_CONNECTION_INIT";
export const SOCKET_CONNECTION_SUCESS = "SOCKET_CONNECTION_SUCCESS";
export const SOCKET_CONNECTION_ERROR = "SOCKET_CONNECTION_ERROR";
export const SOCKET_CONNECTION_CLOSED = "SOCKET_CONNECTION_CLOSED";
export const SOCKET_MESSAGE = "SOCKET_MESSAGE";
